# Chapter 2: Introduction to Machine Learning
ML is about building an algorithm that can perform a certain tasks. The general steps in an ML are:

Get some data
Establish something that should be done with such data (= task)
Find an algorithm that can perform the task
Operationalize the goal by an error metric (=loss) that is to be minimized
Train the algorithm to achieve a small loss on the data
Test the performance of the algorithm


Example
1. data = airquality
2. predict Ozone
3. algorithm = lm
4. loss = residual sum of squares
5. m = lm(Ozone ~ ., data = airquality)
6. could predict(m) to data or hold-out

Our task in the course will now be to better understand
1. What are tasks that we can tackle?
2. What algorithm exist and how can they be set up / tuned / modified
3. How to define the loss and wow to best train the algorithms?
4. How to do the performance evaluation

## 2.1 ML Tasks
There are three types of machine learning tasks:

* Supervised learning
* Unsupervised learning
* Reinforcement learning

1) Supervised learning, you train algorithms to predict something (classes or values = regression) from some other data (= features), and you provide it with correct examples of the execution of the task (called training data). A linear regression is an example of supervised learning.
2) Unsupervised learning, on the other hand, is when you provide the features, but no examples of the correct execution of the task. Clustering techniques are examples of unsupervised learning
3) Reinforcement learning is a technique that mimics a game-like situation. The algorithm finds a solution through trial and error, receiving either rewards or penalties for each action. As in games, the goal is to maximize the rewards. We will talk more about this technique on the last day of the course.

In unsupervised learning, we want to identify patterns in data without having any examples (supervision) about what the correct patterns / classes are. As an example, consider the iris data set. Here, we have 150 observations of 4 floral traits:
```{r}
iris = datasets::iris
colors = hcl.colors(3)
traits = as.matrix(iris[,1:4])
species = iris$Species
image(y = 1:4, x = 1:length(species) , z = traits,
      ylab = "Floral trait", xlab = "Individual")
segments(50.5, 0, 50.5, 5, col = "black", lwd = 2)
segments(100.5, 0, 100.5, 5, col = "black", lwd = 2)
```

